apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs
  labels:
    app: sample-nodejs
spec:
  replicas: 2
  selector:
    matchLabel:
      app: sample-nodejs
  template:
    metadata:
      labels:
        app: sample-nodejs
    spec:
      containers:
        - image: idrisskhaled96/node-hello-world:latest
          name: node-hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  selector:
    app: sample-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer