apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
  labels:
    app: spring-boot-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
        - name: hello-world
          image: idrisskhaled96/hello-world:latest

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world-service
spec:
  selector:
    app: spring-boot-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer